export const SET_LOADING = 'SET_LOADING';
export const FETCH_PETS = 'FETCH_PETS';
export const REGISTER_PET = 'REGISTER_PET';
export const FETCH_CURRENT_PET = 'FETCH_CURRENT_PET';
export const UPDATE_SEARCH_FILTERS = 'UPDATE_SEARCH_FILTERS';
